"""compliance report — polished PDF, generated in-app and downloadable.

This is the monetisation artifact: the dashboard is free, generating the
official report is the paid step (payment gate added later). The `draft` flag
already supports a watermarked free preview vs a clean official report, so the
paywall is a one-line switch when you're ready.

Pure reportlab (no system dependencies) → works on Render / Streamlit Cloud.
Returns PDF bytes; the caller streams them via st.download_button.
"""
from __future__ import annotations

import io
from datetime import date
from typing import List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, PageBreak)

from core.constants import COMPLIANCE_LIMITS, MONTH_NAMES
from core.calculations import check_compliance, monthly_compliance_rate
from core.alert_engine import evaluate_alert_level

NAVY = colors.HexColor("#1B3A5C")
BLUE = colors.HexColor("#2E5D8A")
GREEN = colors.HexColor("#C6EFCE")
GREEN_TX = colors.HexColor("#006100")
RED = colors.HexColor("#FFC7CE")
RED_TX = colors.HexColor("#9C0006")
GREY = colors.HexColor("#555555")

_ATTR = {k: k for k in COMPLIANCE_LIMITS}   # Compliance keys map 1:1 to WaterReading attrs


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("H1", parent=ss["Heading1"], textColor=NAVY, fontSize=18, spaceAfter=4))
    ss.add(ParagraphStyle("Sub", parent=ss["Normal"], textColor=GREY, fontSize=10, spaceAfter=10))
    ss.add(ParagraphStyle("H2", parent=ss["Heading2"], textColor=NAVY, fontSize=13,
                          spaceBefore=12, spaceAfter=6))
    ss.add(ParagraphStyle("Body", parent=ss["Normal"], fontSize=9.5, leading=13))
    ss.add(ParagraphStyle("Foot", parent=ss["Normal"], fontSize=7.5, textColor=GREY))
    return ss


def _watermark(canvas, doc, draft: bool):
    canvas.saveState()
    # Footer
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(GREY)
    canvas.drawString(20 * mm, 12 * mm,
                      "Generated by the GDM Enviro Lagoon Intelligence Platform")
    canvas.drawRightString(190 * mm, 12 * mm, f"Page {doc.page}")
    if draft:
        canvas.setFont("Helvetica-Bold", 60)
        canvas.setFillColor(colors.Color(0.85, 0.85, 0.85, alpha=0.45))
        canvas.translate(105 * mm, 150 * mm)
        canvas.rotate(45)
        canvas.drawCentredString(0, 0, "DRAFT — NOT FOR SUBMISSION")
    canvas.restoreState()


def _summary_table(readings: list, ss) -> Table:
    head = ["Parameter", "Unit", "Compliance Limit", "Avg", "Max", "Min", "Months", "Status"]
    data = [head]
    styles = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F7FA")]),
    ]
    for r_i, (key, lim) in enumerate(COMPLIANCE_LIMITS.items(), start=1):
        vals = [getattr(rr, _ATTR[key]) for rr in readings]
        cm = sum(1 for v in vals if check_compliance(key, v).compliant)
        full = cm == len(vals)
        status = "FULL COMPLIANCE" if full else "EXCEEDANCE"
        data.append([lim.parameter, lim.unit, lim.display,
                     f"{sum(vals)/len(vals):.1f}", f"{max(vals):.1f}", f"{min(vals):.1f}",
                     f"{cm}/{len(vals)}", status])
        bg, tx = (GREEN, GREEN_TX) if full else (RED, RED_TX)
        styles += [("BACKGROUND", (7, r_i), (7, r_i), bg),
                   ("TEXTCOLOR", (7, r_i), (7, r_i), tx),
                   ("FONTNAME", (7, r_i), (7, r_i), "Helvetica-Bold")]
    t = Table(data, colWidths=[34*mm, 16*mm, 24*mm, 13*mm, 13*mm, 13*mm, 15*mm, 32*mm])
    t.setStyle(TableStyle(styles))
    return t


def _exceedance_rows(readings: list) -> list:
    by_month = {r.timestamp.month: r for r in readings}
    rows = [["Month", "Parameter", "Value", "Compliance Limit"]]
    for m in range(1, 13):
        r = by_month.get(m)
        if not r:
            continue
        for key, lim in COMPLIANCE_LIMITS.items():
            res = check_compliance(key, getattr(r, _ATTR[key]))
            if not res.compliant:
                rows.append([MONTH_NAMES[m-1], lim.parameter, f"{res.value}", lim.display])
    return rows


def build_compliance_report(site: str, year: int, readings: list, draft: bool = False) -> bytes:
    """Build the compliance report PDF. Returns PDF bytes."""
    if not readings:
        raise ValueError("No readings to report.")
    ss = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18*mm, bottomMargin=20*mm,
                            leftMargin=18*mm, rightMargin=18*mm,
                            title=f"Compliance Report {site} {year}")
    el = []

    # ── Header ──
    el.append(Paragraph("Water Quality Compliance Report", ss["H1"]))
    el.append(Paragraph(
        f"Site: <b>{site}</b> &nbsp;|&nbsp; Reporting Year: <b>{year}</b> &nbsp;|&nbsp; "
        f"Generated: {date.today().isoformat()} &nbsp;|&nbsp; GDM Enviro Consultants",
        ss["Sub"]))

    # ── Annual scorecard ──
    total_params = len(COMPLIANCE_LIMITS)
    full_params = 0
    for key in COMPLIANCE_LIMITS:
        vals = [getattr(rr, _ATTR[key]) for rr in readings]
        if all(check_compliance(key, v).compliant for v in vals):
            full_params += 1
    overall = monthly_compliance_rate(full_params, total_params)
    el.append(Paragraph("Annual Compliance Scorecard", ss["H2"]))
    el.append(Paragraph(
        f"Overall parameter compliance: <b>{overall:.0f}%</b> "
        f"({full_params}/{total_params} parameters in full compliance across "
        f"{len(readings)} months on record).", ss["Body"]))

    # ── Per-parameter table ──
    el.append(Paragraph("Compliance Summary by Parameter", ss["H2"]))
    el.append(_summary_table(readings, ss))

    # ── Exceedance log ──
    el.append(Paragraph("Exceedance Log", ss["H2"]))
    exc = _exceedance_rows(readings)
    if len(exc) == 1:
        el.append(Paragraph("No exceedances recorded — all parameters remained within "
                            "compliance limits throughout the reporting period.", ss["Body"]))
    else:
        t = Table(exc, colWidths=[24*mm, 40*mm, 28*mm, 30*mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
            ("BACKGROUND", (0, 1), (-1, -1), RED),
            ("TEXTCOLOR", (0, 1), (-1, -1), RED_TX),
        ]))
        el.append(t)

    # ── Bloom risk assessment (client-safe value-add) ──
    el.append(Paragraph("Algae Bloom Risk Assessment", ss["H2"]))
    latest = max(readings, key=lambda r: r.timestamp)
    alert = evaluate_alert_level(latest)
    el.append(Paragraph(
        f"Most recent reading ({MONTH_NAMES[latest.timestamp.month-1]} {latest.timestamp.year}): "
        f"alert level <b>{alert.level}</b>, bloom probability <b>{alert.bloom_probability:.0f}%</b>, "
        f"dominant regime <b>{alert.dominant_species}</b>. "
        + ("Key drivers: " + "; ".join(alert.top_drivers) + "." if alert.top_drivers
           else "All parameters within normal operating range."),
        ss["Body"]))

    # ── Attestation ──
    el.append(Spacer(1, 10*mm))
    el.append(Paragraph(
        "<i>This report summarises water quality monitoring data against Compliance / Dubai "
        "Municipality limits. Prepared by GDM Enviro Consultants for regulatory "
        "compliance purposes.</i>", ss["Foot"]))

    doc.build(el, onFirstPage=lambda c, d: _watermark(c, d, draft),
              onLaterPages=lambda c, d: _watermark(c, d, draft))
    return buf.getvalue()
